#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
echo Moving files from /public to /php...
rm -rf $OPENSHIFT_REPO_DIRphp/*
cp -r $OPENSHIFT_REPO_DIRpublic/* $OPENSHIFT_REPO_DIRphp/
